
server:
  port: 9000
  servlet:
    context-path: /sso-server
    session:
      timeout: 30m
spring:
  application:
    name: sso-server
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false